version: "3"
services:
  database:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: share-music
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  database-data:
