name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - ".dockerignore"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/vitrola
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn build
      - run: yarn prisma:deploy
      - run: yarn test
